server:
  port: 7080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crazy_task_api
    username: bestuser
    password: bestuser
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true